name: mlp_lstm
dependencies:
  - python=3.7
  - numpy=1.19.2
  - pandas=1.2.3
  - pytest=6.2.2 
  - pytest-cov=2.11.1
  - mypy=0.812
  - jupyterlab=2.2.6
  - plotly=4.14.3
  - seaborn=0.11.1
  - matplotlib=3.3.4
  - pip=21.0.1
  - pip:
    - torchvision
    - pandas_datareader==0.9.0
    - tensorflow==2.4.1
variables:
  KMP_DUPLICATE_LIB_OK: True