name: mlp_lstm
dependencies:
  - python=3.8
  - numpy=1.19.*
  - pandas=1.2.*
  - pytest
  - pytest-cov
  - coverage
  - mypy
  - jupyterlab
  - pandas-datareader
  - plotly
  - seaborn
  - matplotlib
  - pip
  - pip:
    - torchvision
